### ISSUE TITLE
Will this repository ever be taken down by the authorities soon?

### ISSUE THREAD

**Issue by KnightChaser** [I-S00N/I-S00N#36]
I wonder how GitHub would react to this repository after some "claims" from the official authorities.

(I also saw the empire's many "faithful" citizens infuriated about this repository. I guess it's been a while since I saw funny things on GitHub, and here's a funny thing!)

**Comment by khanhmuy** [comment]
this is the funniest thing ive seen on github in a while lmfao

**Comment by Rairof** [comment]
![image](https://github.com/I-S00N/I-S00N/assets/107706560/548e60ff-717e-4873-ace3-9b032c738677)
Ya really think so?

**Comment by C0ntr07** [comment]
Paranoid much?

**Comment by demoliisher** [comment]
i don't mind, i'll backup it

**Comment by itsvrl** [comment]
海外大笑🤣

**Comment by KnightChaser** [comment]
Well actually I don't care what they would say, I just saved that as ZIP

**Comment by khanhmuy** [comment]
>china do what china wants; anyone who has ever interacted with this repo is on a watch list
>
>don't sign up for wechat guys!

they ass aint doing shit 😭

**Comment by ShoelessTom** [comment]
> ![image](https://private-user-images.githubusercontent.com/107706560/306299159-548e60ff-717e-4873-ace3-9b032c738677.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODc5NDcsIm5iZiI6MTcwODQ4NzY0NywicGF0aCI6Ii8xMDc3MDY1NjAvMzA2Mjk5MTU5LTU0OGU2MGZmLTcxN2UtNDg3My1hY2UzLTliMDMyYzczODY3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwMzU0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjEwY2VkYjdjNGU1MGE2Yzc0MzY2NTFhNzQ1YzAwODMxY2FkOTY5NmQ2M2NiNjIyYjY0MTQ2ZmVhYzljMjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zZQGDUuQt0M1PzN6oZ_ow54uRwlIpH2dmOPR4vnhz4c) Ya really think so?

They can mass delete forks, best to gitclone or download as zip

**Comment by Rairof** [comment]
https://github.com/I-S00N/I-S00N/issues/36#issuecomment-1955841513
Just go on internet archive and you will see how much this page has been recorded
