### ISSUE TITLE
成都也有一家（一石数字技术成都有限公司）

### ISSUE THREAD

**Issue by nightzjp** [I-S00N/I-S00N#7]
公司骗国家的钱，伪造各种合同，文档。
垫付不报销。各种画饼。最后死不认账。领导还都是关系户。整天严抓考勤

**Comment by zhangruiyuan022499** [comment]
陌生人，虽然跟你们无关系，但是呢如果愿意说还是想看看你知道的公司瓜保熟不？也可在github上post。
@nightzjp

**Comment by nightzjp** [comment]
我改天分享一个pdf版本的🙂

| |
seven_nighter
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年02月19日 21:47 |
| 收件人 | I-S00N/I-S00N ***@***.***> |
| 抄送人 | ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [I-S00N/I-S00N] 成都也有一家（一石数字技术成都有限公司） (Issue #7) |

陌生人，虽然跟你们无关系，但是呢如果愿意说还是想看看你知道的公司瓜保熟不？也可在github上post。
@nightzjp
